package com.producto4.model;
// Generated 9 ene. 2022 16:34:58 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "Sede")
public class Sede  implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "id")
     private int id;
    @Column(name = "ubicacion")
     private String ubicacion;
    @Column(name = "tipo")
     private String tipo;

    public Sede() {
    }

    public Sede(int id, String ubicacion, String tipo) {
        this.id = id;
        this.ubicacion = ubicacion;
        this.tipo = tipo;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Sede other = (Sede) obj;
        if (!Objects.equals(this.ubicacion, other.ubicacion)) {
            return false;
        }
        if (!Objects.equals(this.tipo, other.tipo)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Sede{" + "id=" + id + ", ubicacion=" + ubicacion + ", tipo=" + tipo + '}';
    }

   



}


